/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as TechnologyRouteImport } from './routes/technology'
import { Route as ResortRevenueRouteImport } from './routes/resort-revenue'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as HowItWorksRouteImport } from './routes/how-it-works'
import { Route as GeofenceRouteImport } from './routes/geofence'
import { Route as DisclaimerRouteImport } from './routes/disclaimer'
import { Route as DemoRequestRouteImport } from './routes/demo-request'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiPublicResortLeadRouteImport } from './routes/api/public/resort-lead'
import { Route as ApiPublicDiscoveryInquiryRouteImport } from './routes/api/public/discovery-inquiry'
import { Route as ApiPublicDemoRequestRouteImport } from './routes/api/public/demo-request'
import { Route as ApiPublicContactInquiryRouteImport } from './routes/api/public/contact-inquiry'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const TechnologyRoute = TechnologyRouteImport.update({
  id: '/technology',
  path: '/technology',
  getParentRoute: () => rootRouteImport,
} as any)
const ResortRevenueRoute = ResortRevenueRouteImport.update({
  id: '/resort-revenue',
  path: '/resort-revenue',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const HowItWorksRoute = HowItWorksRouteImport.update({
  id: '/how-it-works',
  path: '/how-it-works',
  getParentRoute: () => rootRouteImport,
} as any)
const GeofenceRoute = GeofenceRouteImport.update({
  id: '/geofence',
  path: '/geofence',
  getParentRoute: () => rootRouteImport,
} as any)
const DisclaimerRoute = DisclaimerRouteImport.update({
  id: '/disclaimer',
  path: '/disclaimer',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoRequestRoute = DemoRequestRouteImport.update({
  id: '/demo-request',
  path: '/demo-request',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicResortLeadRoute = ApiPublicResortLeadRouteImport.update({
  id: '/api/public/resort-lead',
  path: '/api/public/resort-lead',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicDiscoveryInquiryRoute =
  ApiPublicDiscoveryInquiryRouteImport.update({
    id: '/api/public/discovery-inquiry',
    path: '/api/public/discovery-inquiry',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicDemoRequestRoute = ApiPublicDemoRequestRouteImport.update({
  id: '/api/public/demo-request',
  path: '/api/public/demo-request',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicContactInquiryRoute = ApiPublicContactInquiryRouteImport.update({
  id: '/api/public/contact-inquiry',
  path: '/api/public/contact-inquiry',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/demo-request': typeof DemoRequestRoute
  '/disclaimer': typeof DisclaimerRoute
  '/geofence': typeof GeofenceRoute
  '/how-it-works': typeof HowItWorksRoute
  '/onboarding': typeof OnboardingRoute
  '/privacy': typeof PrivacyRoute
  '/resort-revenue': typeof ResortRevenueRoute
  '/technology': typeof TechnologyRoute
  '/terms': typeof TermsRoute
  '/api/public/contact-inquiry': typeof ApiPublicContactInquiryRoute
  '/api/public/demo-request': typeof ApiPublicDemoRequestRoute
  '/api/public/discovery-inquiry': typeof ApiPublicDiscoveryInquiryRoute
  '/api/public/resort-lead': typeof ApiPublicResortLeadRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/demo-request': typeof DemoRequestRoute
  '/disclaimer': typeof DisclaimerRoute
  '/geofence': typeof GeofenceRoute
  '/how-it-works': typeof HowItWorksRoute
  '/onboarding': typeof OnboardingRoute
  '/privacy': typeof PrivacyRoute
  '/resort-revenue': typeof ResortRevenueRoute
  '/technology': typeof TechnologyRoute
  '/terms': typeof TermsRoute
  '/api/public/contact-inquiry': typeof ApiPublicContactInquiryRoute
  '/api/public/demo-request': typeof ApiPublicDemoRequestRoute
  '/api/public/discovery-inquiry': typeof ApiPublicDiscoveryInquiryRoute
  '/api/public/resort-lead': typeof ApiPublicResortLeadRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/demo-request': typeof DemoRequestRoute
  '/disclaimer': typeof DisclaimerRoute
  '/geofence': typeof GeofenceRoute
  '/how-it-works': typeof HowItWorksRoute
  '/onboarding': typeof OnboardingRoute
  '/privacy': typeof PrivacyRoute
  '/resort-revenue': typeof ResortRevenueRoute
  '/technology': typeof TechnologyRoute
  '/terms': typeof TermsRoute
  '/api/public/contact-inquiry': typeof ApiPublicContactInquiryRoute
  '/api/public/demo-request': typeof ApiPublicDemoRequestRoute
  '/api/public/discovery-inquiry': typeof ApiPublicDiscoveryInquiryRoute
  '/api/public/resort-lead': typeof ApiPublicResortLeadRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/dashboard'
    | '/demo-request'
    | '/disclaimer'
    | '/geofence'
    | '/how-it-works'
    | '/onboarding'
    | '/privacy'
    | '/resort-revenue'
    | '/technology'
    | '/terms'
    | '/api/public/contact-inquiry'
    | '/api/public/demo-request'
    | '/api/public/discovery-inquiry'
    | '/api/public/resort-lead'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/dashboard'
    | '/demo-request'
    | '/disclaimer'
    | '/geofence'
    | '/how-it-works'
    | '/onboarding'
    | '/privacy'
    | '/resort-revenue'
    | '/technology'
    | '/terms'
    | '/api/public/contact-inquiry'
    | '/api/public/demo-request'
    | '/api/public/discovery-inquiry'
    | '/api/public/resort-lead'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact'
    | '/dashboard'
    | '/demo-request'
    | '/disclaimer'
    | '/geofence'
    | '/how-it-works'
    | '/onboarding'
    | '/privacy'
    | '/resort-revenue'
    | '/technology'
    | '/terms'
    | '/api/public/contact-inquiry'
    | '/api/public/demo-request'
    | '/api/public/discovery-inquiry'
    | '/api/public/resort-lead'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  DashboardRoute: typeof DashboardRoute
  DemoRequestRoute: typeof DemoRequestRoute
  DisclaimerRoute: typeof DisclaimerRoute
  GeofenceRoute: typeof GeofenceRoute
  HowItWorksRoute: typeof HowItWorksRoute
  OnboardingRoute: typeof OnboardingRoute
  PrivacyRoute: typeof PrivacyRoute
  ResortRevenueRoute: typeof ResortRevenueRoute
  TechnologyRoute: typeof TechnologyRoute
  TermsRoute: typeof TermsRoute
  ApiPublicContactInquiryRoute: typeof ApiPublicContactInquiryRoute
  ApiPublicDemoRequestRoute: typeof ApiPublicDemoRequestRoute
  ApiPublicDiscoveryInquiryRoute: typeof ApiPublicDiscoveryInquiryRoute
  ApiPublicResortLeadRoute: typeof ApiPublicResortLeadRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/technology': {
      id: '/technology'
      path: '/technology'
      fullPath: '/technology'
      preLoaderRoute: typeof TechnologyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resort-revenue': {
      id: '/resort-revenue'
      path: '/resort-revenue'
      fullPath: '/resort-revenue'
      preLoaderRoute: typeof ResortRevenueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-it-works': {
      id: '/how-it-works'
      path: '/how-it-works'
      fullPath: '/how-it-works'
      preLoaderRoute: typeof HowItWorksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/geofence': {
      id: '/geofence'
      path: '/geofence'
      fullPath: '/geofence'
      preLoaderRoute: typeof GeofenceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/disclaimer': {
      id: '/disclaimer'
      path: '/disclaimer'
      fullPath: '/disclaimer'
      preLoaderRoute: typeof DisclaimerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo-request': {
      id: '/demo-request'
      path: '/demo-request'
      fullPath: '/demo-request'
      preLoaderRoute: typeof DemoRequestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/resort-lead': {
      id: '/api/public/resort-lead'
      path: '/api/public/resort-lead'
      fullPath: '/api/public/resort-lead'
      preLoaderRoute: typeof ApiPublicResortLeadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/discovery-inquiry': {
      id: '/api/public/discovery-inquiry'
      path: '/api/public/discovery-inquiry'
      fullPath: '/api/public/discovery-inquiry'
      preLoaderRoute: typeof ApiPublicDiscoveryInquiryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/demo-request': {
      id: '/api/public/demo-request'
      path: '/api/public/demo-request'
      fullPath: '/api/public/demo-request'
      preLoaderRoute: typeof ApiPublicDemoRequestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/contact-inquiry': {
      id: '/api/public/contact-inquiry'
      path: '/api/public/contact-inquiry'
      fullPath: '/api/public/contact-inquiry'
      preLoaderRoute: typeof ApiPublicContactInquiryRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  DashboardRoute: DashboardRoute,
  DemoRequestRoute: DemoRequestRoute,
  DisclaimerRoute: DisclaimerRoute,
  GeofenceRoute: GeofenceRoute,
  HowItWorksRoute: HowItWorksRoute,
  OnboardingRoute: OnboardingRoute,
  PrivacyRoute: PrivacyRoute,
  ResortRevenueRoute: ResortRevenueRoute,
  TechnologyRoute: TechnologyRoute,
  TermsRoute: TermsRoute,
  ApiPublicContactInquiryRoute: ApiPublicContactInquiryRoute,
  ApiPublicDemoRequestRoute: ApiPublicDemoRequestRoute,
  ApiPublicDiscoveryInquiryRoute: ApiPublicDiscoveryInquiryRoute,
  ApiPublicResortLeadRoute: ApiPublicResortLeadRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
